
services:
  backend:
    image: ipeyu-backend-admin  # The image name from your Docker build
    build: .  # Builds from the Dockerfile in the current directory
    container_name: iPeyU-backend
    ports:
      - "8009:8008"  # Map container port 8008 to host port 8008
    depends_on:
      mysql : # Ensures MySQL starts first
        condition: service_healthy  # Ensure MySQL is fully running
    environment:
      - SERVER_PORT=8008
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AES_ENCRYPTION_KEY=${AES_ENCRYPTION_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
      - PAY_SPRINT_BASE_URL=${PAY_SPRINT_BASE_URL}
      - PAY_SPRINT_JWT_KEY=${PAY_SPRINT_JWT_KEY}
      - PAY_SPRINT_AUTHORIZED_KEY=${PAY_SPRINT_AUTHORIZED_KEY}
      - PAY_SPRINT_PARTNER_ID=${PAY_SPRINT_PARTNER_ID}
      - SCRIZA_BASE_URL=${SCRIZA_BASE_URL}
      - SCRIZA_API_TOKEN=${SCRIZA_API_TOKEN}
    restart: always
    volumes:
      - ./target/iPeyu-Backend-admin-1.1.0.jar:/app/app.jar  # Mount JAR file

  mysql:
    image: mysql:8.0
    container_name: mysql-docker
    ports:
      - "3308:3306"  # Expose MySQL port
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ipeyudb_docker
    volumes:
      - mysql_data:/var/lib/mysql  # Persist database data
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:  # Named volume for MySQL persistence
