name: CI/CD Pipeline

on:
  push:
    branches: ["production-ec2"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Sources
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create Firebase Configuration File
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_FILE }}" | base64 --decode > ipeyu-firebase-admin-sdk.json

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


      - name: Build the Spring Boot application
        run: mvn clean package -DskipTests

      - name: Build the Docker image
        run: docker build --build-arg JAR_FILE=target/iPeyu-Backend-admin-1.1.0.jar -t heterophyllustechnologyllp/ipeyu-backend-admin:latest .

      - name: Verify Image Exists
        run: docker images

      - name: Push To Docker Hub
        run: docker push heterophyllustechnologyllp/ipeyu-backend-admin:latest

  deploy:
    needs: build-and-deploy
    runs-on: self-hosted

    steps:
      - name: Pull Latest Docker Image
        run: docker pull heterophyllustechnologyllp/ipeyu-backend-admin:latest

      - name: Delete Old Docker Container
        run: docker rm -f ipeyu-backend-admin-container || true

      - name: Run Docker Container
        run:  docker run -d --name ipeyu-backend-admin-container -p 8009:8008 heterophyllustechnologyllp/ipeyu-backend-admin:latest


