name: Docker Image CI

on:
  push:
    branches: [ "production-ec2" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build -t ipeyu-backend-admin .
      - name: Push To Docker Hub
        run: docker push heterophyllustechnologyllp/ipeyu-backend-admin:latest