name: CI Pipeline

on:
  push:
    branches: [ "production-ec2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build the Docker image
        run: docker build -t heterophyllustechnologyllp/ipeyu-backend-admin:latest .

      - name: Verify Image Exists
        run: docker images

      - name: Push To Docker Hub
        run: docker push heterophyllustechnologyllp/ipeyu-backend-admin:latest
